/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PalindromeChecker */

#ifndef _Included_PalindromeChecker
#define _Included_PalindromeChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PalindromeChecker
 * Method:    isPalindrome
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_PalindromeChecker_isPalindrome
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
